/*
 * CountriesAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using CountriesAPI.Standard.Controllers;
using CountriesAPI.Standard.Http.Client;
using CountriesAPI.Standard.Utilities;

namespace CountriesAPI.Standard
{
    public partial class CountriesAPIClient
    {

        /// <summary>
        /// Singleton access to Countries controller
        /// </summary>
        public CountriesController Countries
        {
            get
            {
                return CountriesController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public CountriesAPIClient() { }
        #endregion
    }
}