/*
 * CountriesAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using CountriesAPI.Standard;
using CountriesAPI.Standard.Utilities;
using CountriesAPI.Standard.Http.Request;
using CountriesAPI.Standard.Http.Response;
using CountriesAPI.Standard.Http.Client;
using CountriesAPI.Standard.Exceptions;

namespace CountriesAPI.Standard.Controllers
{
    public partial class CountriesController: BaseController
    {
        #region Singleton Pattern

        //private static variables for the singleton pattern
        private static object syncObject = new object();
        private static CountriesController instance = null;

        /// <summary>
        /// Singleton pattern implementation
        /// </summary>
        internal static CountriesController Instance
        {
            get
            {
                lock (syncObject)
                {
                    if (null == instance)
                    {
                        instance = new CountriesController();
                    }
                }
                return instance;
            }
        }

        #endregion Singleton Pattern

        /// <summary>
        /// This endpoint let user to access countries code and name.
        /// </summary>
        /// <return>Returns the Models.CountryResponse response from the API call</return>
        public Models.CountryResponse GetCountries()
        {
            Task<Models.CountryResponse> t = GetCountriesAsync();
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// This endpoint let user to access countries code and name.
        /// </summary>
        /// <return>Returns the Models.CountryResponse response from the API call</return>
        public async Task<Models.CountryResponse> GetCountriesAsync()
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/countries");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" }
            };

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Get(_queryUrl,_headers);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<Models.CountryResponse>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

    }
} 